# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('charityName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('jobcode', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('jax', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PairingSignupData',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('jobcode', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('experiences', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
