# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0003_auto_20170621_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingSignupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('experiences', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
