# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0004_pairingsignupdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairingsignupdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='pairingsignupdata',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
