# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0005_pairing_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairing',
            name='img',
        ),
    ]
