# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0006_auto_20170623_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairingsignupdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pairingsignupdata',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairingsignupdata',
            name='experiences',
            field=models.CharField(max_length=100),
        ),
    ]
