# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0007_auto_20170623_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairingsignupdata',
            name='experiences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
