# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0008_auto_20170624_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='jobcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pairingsignupdata',
            name='jobcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
