# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_auto_20170623_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(blank=True, default='static/img/None/no-img.jpg', null=True, upload_to='static/img/'),
        ),
    ]
