# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_auto_20170623_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='model_pic',
        ),
    ]
