# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 06:10
from __future__ import unicode_literals

import charity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_remove_post_model_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=charity.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='post',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
