# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tracklah.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityOrg',
            fields=[
                ('charityName', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200, null=True)),
                ('postalCode', models.IntegerField()),
                ('contactNum', models.IntegerField()),
                ('emailAddr', models.EmailField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='CharityProjMain',
            fields=[
                ('projectNameMain', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('projectDir', models.CharField(max_length=200, null=True)),
                ('dateStarted', models.DateField(null=True)),
                ('dateCompleted', models.DateField(null=True)),
                ('charityName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracklah.CharityOrg')),
            ],
        ),
        migrations.CreateModel(
            name='CharityProjSub',
            fields=[
                ('projectNameSub', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('shortWriteup', models.TextField(null=True)),
                ('infoWindowWriteup', models.TextField(null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('lat', models.FloatField(max_length=200, null=True)),
                ('lng', models.FloatField(max_length=200, null=True)),
                ('zoom', models.IntegerField()),
                ('dateStarted', models.DateField(null=True)),
                ('dateCompleted', models.DateField(null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to=tracklah.models.upload_location)),
                ('img2', models.ImageField(blank=True, null=True, upload_to=tracklah.models.upload_location)),
                ('img3', models.ImageField(blank=True, null=True, upload_to=tracklah.models.upload_location)),
                ('videoLink', models.URLField(blank=True, null=True)),
                ('charityName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracklah.CharityOrg')),
                ('projectNameMain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracklah.CharityProjMain')),
            ],
        ),
        migrations.CreateModel(
            name='ChocoCode',
            fields=[
                ('donationCode', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('currNumUser', models.IntegerField(default=1)),
                ('maxNumUsers', models.IntegerField(default=1)),
                ('charityOrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracklah.CharityOrg')),
                ('projectNameMain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracklah.CharityProjMain')),
                ('projectNameSub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracklah.CharityProjSub')),
            ],
        ),
    ]
