# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracklah', '0002_charpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='charpost',
            name='clat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='charpost',
            name='clng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
