# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracklah', '0004_charityprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityprojects',
            name='chocoBarCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
