# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracklah', '0005_charityprojects_chocobarcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charityprojects',
            name='chocoBarCode',
        ),
        migrations.AddField(
            model_name='charpost',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='tracklah/static/img'),
        ),
        migrations.AddField(
            model_name='charpost',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='tracklah/static/img'),
        ),
    ]
