# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracklah', '0007_auto_20170717_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charpost',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='tracklah/static/img', verbose_name='initial_picture'),
        ),
        migrations.AlterField(
            model_name='charpost',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='tracklah/static/img', verbose_name='initial_picture'),
        ),
    ]
