# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracklah', '0009_auto_20170717_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='charpost',
            name='img2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
