# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import tracklah.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracklah', '0010_charpost_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charpost',
            name='img1',
            field=models.ImageField(blank=True, height_field=250, null=True, upload_to=tracklah.models.upload_location, width_field=250),
        ),
        migrations.AlterField(
            model_name='charpost',
            name='img2',
            field=models.ImageField(blank=True, height_field=250, null=True, upload_to=tracklah.models.upload_location, width_field=250),
        ),
    ]
