# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import tracklah.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracklah', '0011_auto_20170717_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='charpost',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charpost',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charpost',
            name='img1',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=tracklah.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='charpost',
            name='img2',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=tracklah.models.upload_location, width_field='width_field'),
        ),
    ]
