# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracklah', '0012_auto_20170717_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charpost',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='charpost',
            name='img2',
        ),
    ]
