# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracklah', '0013_auto_20170718_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityprojects',
            name='chocoCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
