# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracklah', '0014_charityprojects_chococode'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityprojects',
            name='shortDescrip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
