# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracklah', '0017_auto_20170723_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charpost',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='charpost',
            name='img2',
        ),
    ]
